# Generated by Django 4.1.3 on 2023-03-16 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TXNID', models.CharField(max_length=200)),
                ('BANKTXNID', models.BigIntegerField()),
                ('ORDERID', models.CharField(max_length=20, unique=True)),
                ('TXNAMOUNT', models.FloatField()),
                ('STATUS', models.CharField(max_length=50)),
                ('TXNTYPE', models.CharField(max_length=20)),
                ('PAYMENTMODE', models.CharField(max_length=200)),
                ('REFUNDAMT', models.FloatField()),
                ('TXNDATE', models.DateTimeField()),
            ],
        ),
    ]
